export const actionType = {
  SET_DATA: "SET_DATA",
  UPDATE_BOOKMARK: 'UPDATE_BOOKMARK',
  DELETE_RESTAURANT: 'DELETE_RESTAURANT',
  DELETE_RESTAURANT_BOOKMARK: 'DELETE_RESTAURANT_BOOKMARK',
  SET_LOGIN: 'SET_LOGIN',
  SET_LOGOUT: 'SET_LOGOUT'
};
